set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "CPack packaging exercise")
set(CPACK_PACKAGE_DESCRIPTION "This is the elaboration for the CPACK packaging exercise by Marcel Graf")

set(CPACK_PACKAGE_VENDOR "Marcel Graf")
set(CPACK_PACKAGE_CONTACT "st172528@stud.uni-stuttgart.de")
set(CPACK_PACKAGE_MAINTAINERS ${CPACK_PACKAGE_VENDOR})

set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/MarcelGraf0710/cpack-exercise-wt2526")

set(CPACK_STRIP_FILES "TRUE")

set(CPACK_BINARY_DEB "ON")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TZ "OFF")
set(CPACK_BINARY_STGZ "OFF")

set(CPACK_DEB_COMPONENT_INSTALL "ON")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

include(CPack)